version: '3.9'

services:
  php-nginx:
    build:
      dockerfile: ./docker/php-nginx/Dockerfile
      context: .
    depends_on:
      - database
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=english-helper.local
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=-1
#      - XDEBUG_MODE=debug
#      - XDEBUG_START_WITH_REQUEST=yes
#      - XDEBUG_CLIENT_PORT=9000
    ports:
      - ${NGINX_PORT:-8080}:80
    env_file:
      - .env
    volumes:
      - ./app/:/app/
      - .env:/app/.env
    networks:
      - app

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  vendor:
